// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPiuqSrhipl1P18Z3qtKEdC7Wssooim7w',
    appId: '1:911867035497:web:4b2ae65bc1a690678707f8',
    messagingSenderId: '911867035497',
    projectId: 'smartprep-4369b',
    authDomain: 'smartprep-4369b.firebaseapp.com',
    storageBucket: 'smartprep-4369b.firebasestorage.app',
    measurementId: 'G-KBB05Y28XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TzknoyKkiLBURvTYFKYvKaBMVQsU7bg',
    appId: '1:911867035497:android:fce018392d7d976e8707f8',
    messagingSenderId: '911867035497',
    projectId: 'smartprep-4369b',
    storageBucket: 'smartprep-4369b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQhpm5zG9Fttcn7ns34AAwSt6xhZbY10',
    appId: '1:911867035497:ios:6750dfec3096d4318707f8',
    messagingSenderId: '911867035497',
    projectId: 'smartprep-4369b',
    storageBucket: 'smartprep-4369b.firebasestorage.app',
    iosBundleId: 'com.example.smartprep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQhpm5zG9Fttcn7ns34AAwSt6xhZbY10',
    appId: '1:911867035497:ios:6750dfec3096d4318707f8',
    messagingSenderId: '911867035497',
    projectId: 'smartprep-4369b',
    storageBucket: 'smartprep-4369b.firebasestorage.app',
    iosBundleId: 'com.example.smartprep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPiuqSrhipl1P18Z3qtKEdC7Wssooim7w',
    appId: '1:911867035497:web:d0543942834315108707f8',
    messagingSenderId: '911867035497',
    projectId: 'smartprep-4369b',
    authDomain: 'smartprep-4369b.firebaseapp.com',
    storageBucket: 'smartprep-4369b.firebasestorage.app',
    measurementId: 'G-2H1DFRL60D',
  );
}
